version: '3.8'

services:
 php:
  image: php:7.2-apache
  ports: 
  - 8006:80
  volumes:
  - ./html:/var/www/html

front:
   build: .
   tty: true
   ports:
   - "3000:3000" # 開発用
   volumes:
   - ./app/profile-site:/app # ./app/{プロジェクト名}:/app
   command: yarn dev



